services:
  app:
    image: ghcr.io/itsubaki/quasar
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - PROJECT_ID=${PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials.json
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/credentials.json:ro
