name: auth switch

on:
  workflow_dispatch:
    inputs:
      service:
        required: true
        default: 'quasar'
      region:
        required: true
        default: 'asia-northeast1'
      switch:
        required: true
        default: 'public'
        type: choice
        options:
          - 'public'
          - 'private'

jobs:
  switch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"
          echo "::add-mask::${{ secrets.SERVICE_URL }}"

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Switch
        run: |
          SERVICE_NAME=${{ github.event.inputs['service'] }}
          REGION=${{ github.event.inputs['region'] }}
          SWITCH=${{ github.event.inputs['switch'] }}

          FLAG="--allow-unauthenticated"
          if [ "$SWITCH" == "private" ]; then
            FLAG="--no-allow-unauthenticated"
          fi

          gcloud run services update ${SERVICE_NAME} --region ${REGION} ${FLAG}

          echo "Cloud Run ${SERVICE_NAME} switched to ${SWITCH} mode"
