name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      authenticate:
        required: true
        default: 'private'
        type: choice
        options:
          - 'public'
          - 'private'

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"
          echo "::add-mask::${{ secrets.SERVICE_URL }}"

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Integration Tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          make install
          make gen
          make test

      - name: Unit Tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          make testpkg

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"
          echo "::add-mask::${{ secrets.SERVICE_URL }}"

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          make install
          make gen
          make build

      - name: Deploy to Google Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            FLAG="--allow-unauthenticated"

            SWITCH=${{ github.event.inputs['authenticate'] }}
            if [ "$SWITCH" == "private" ]; then
              FLAG="--no-allow-unauthenticated"
            fi
          fi

          AUTHENTICATE_FLAG=${FLAG} make deploy
