name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"
          echo "::add-mask::${{ secrets.SERVICE_URL }}"

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Integration Tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          make test

      - name: Unit Tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          make testpkg

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"
          echo "::add-mask::${{ secrets.SERVICE_URL }}"

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/quasar
        run: |
          make build

      - name: Deploy to Google Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/quasar
        run: |
          make deploy
