name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

concurrency: tests

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"

      - name: Integration Tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo ${GOOGLE_APPLICATION_CREDENTIALS} > ./credentials.json
          make test
          rm -rf ./credentials/json

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Deploying to Google Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          service: "fourkeys"
          image: "gcr.io/${PROJECT_ID}/quasar"
