name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

concurrency: tests

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout
        uses: actions/checkout@v2

      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PROJECT_ID }}"
          echo "::add-mask::${{ secrets.SERVICE_URL }}"

      - name: Auth Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Integration Tests
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          make test

      - name: Build image
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/quasar
        run: |
          make build

      - name: Deploy to Google Cloud Run
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          IMAGE: gcr.io/${{ secrets.PROJECT_ID }}/quasar
        run: |
          make deploy
